config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :setting, only: [:show]
  resource :data_source, only: [:edit, :update]

  resources :videos, only: [:index]
  resources :playlists
  resources :playlist_videos, only: [:create, :update, :destroy]

  resources :fetch_requests, only: [:index, :create, :update]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/data_source.rb
class DataSource < ApplicationRecord
  has_many :fetch_requests, dependent: :destroy
  has_many :videos, dependent: :destroy

  validates :url, presence: true, uniqueness: true, format: { with: URI::regexp(%w(http https)) }

  class << self
    def instance
      DataSource.first || create(url: Setting.youtube_api)
    end
  end
end

app/controllers/data_sources_controller.rb
class DataSourcesController < ApplicationController
  before_action :data_source

  def edit
  end

  def update
    if data_source.update(data_source_params)
      notice = t("flash.data_source.update.success")
      respond_to do |format|
        format.html { redirect_to setting_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def data_source_params
    params.require(:data_source).permit(:url)
  end
end

app/views/data_sources/_data_source.html.erb
<%= turbo_frame_tag dom_id(data_source) do %>
  <h5 class="card-title"><%= data_source.class.human_attribute_name(:url) %></h5>
  <p class="card-text"><%= data_source.url %></p>

  <%= link_to t('actions.edit'), edit_data_source_path, class: "btn btn-primary" %>
  <%= link_to t('actions.fetch_videos'), fetch_requests_path, class: "btn btn-primary", data: { turbo_method: :post, turbo_prefetch: false, turbo_frame: "_top" } %>
  <%= link_to FetchRequest.model_name.human(count: 2), fetch_requests_path, class: "btn btn-primary", data: { turbo_prefetch: false, turbo_frame: "_top" } %>
<% end %>

app/views/data_sources/_form.html.erb
<%= simple_form_for data_source, url: data_source_path, method: :put do |f| %>
  <%= f.input :url %>
  <%= f.button :submit, t("helpers.submit.update"), class: 'btn btn-primary mx-1' %>
  <%= link_to t("actions.cancel"), setting_path, class: 'btn btn-secondary' %>
<% end %>

app/views/data_sources/edit.html.erb
<%= content_for(:breadcrumbs) do %>
  <% render("layouts/breadcrumbs/breadcrumbs", links: [{ title: t("navigation.settings"), url: setting_path }, { title: t('data_source.edit.title') }]) %>
<% end %>

<h3><%= t('data_source.edit.title') %></h3>

<%= turbo_frame_tag dom_id(@data_source) do %>
  <%= render "form", data_source: @data_source %>
<% end %>

app/views/data_sources/edit.turbo_stream.erb
<%= turbo_stream.replace dom_id(@data_source) do %>
  <%= render "form", data_source: @data_source %>
<% end %>

app/views/data_sources/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@data_source) do %>
  <%= render "data_source", data_source: @data_source %>
<% end %>

<%= render_turbo_stream_flash_messages %>