config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :setting, only: [:show]
  resource :data_source, only: [:edit, :update]

  resources :videos, only: [:index]
  resources :playlists
  resources :playlist_videos, only: [:create, :update, :destroy]

  resources :fetch_requests, only: [:index, :create, :update]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/fetch_request.rb
class FetchRequest < ApplicationRecord
  enum status: %w(processing done error)

  belongs_to :data_source

  scope :latest, -> { order(id: :desc) }
  scope :active, -> { where(status: 'processing') }

  class << self
    def active_count
      active.count
    end
  end
end

app/controllers/fetch_requests_controller.rb
class FetchRequestsController < ApplicationController
  def index
    @pagy, @fetch_requests = pagy(FetchRequest.latest, items: 10)
  end

  def create
    fetcher = Videos::Fetcher.new

    result = fetcher.call(data_source)

    if result.status
      notice = t("flash.fetch_requests.create.success")
      respond_to do |format|
        format.html { redirect_to setting_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    else
      error = t("flash.fetch_requests.create.error", reason: result.error)
      respond_to do |format|
        format.html { redirect_to setting_path, flash: { error: error } }
        format.turbo_stream do
          flash.now[:error] = error
          render :create, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    fetch_request = FetchRequest.find(params[:id])

    fetcher = Videos::Fetcher.new

    result = fetcher.restart(fetch_request)

    if result.status
      notice = t("flash.fetch_requests.update.success")
      respond_to do |format|
        format.html { redirect_to fetch_requests_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    else
      error = t("flash.fetch_requests.update.error", reason: result.error)
      respond_to do |format|
        format.html { redirect_to fetch_requests_path, flash: { error: error } }
        format.turbo_stream do
          flash.now[:error] = error
          render :create, status: :unprocessable_entity
        end
      end
    end
  end
end

app/helpers/fetch_requests_helper.rb
module FetchRequestsHelper
  def request_status_badge(value)
    color_class = {
      'processing' => 'text-bg-secondary',
      'done' => 'text-bg-success',
      'error' => 'text-bg-danger'
    }[value]

    badge(t("fetch_requests.statuses.#{value}"), color_class, uppercase: true)
  end
end

app/views/fetch_requests/_error_modal.html.erb
<div class="modal" tabindex="-1" id="fetch-request-log">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= FetchRequest.human_attribute_name("log") %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body overflow-auto max-vh-100">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><%= t('actions.close')  %></button>
      </div>
    </div>
  </div>
</div>

app/views/fetch_requests/_records.html.erb
<% if @fetch_requests.size > 0 %>
<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th scope="col"><%= FetchRequest.human_attribute_name("created_at") %></th>
      <th scope="col"><%= FetchRequest.human_attribute_name("status") %></th>
      <th scope="col"><%= FetchRequest.human_attribute_name("page") %></th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @fetch_requests.each do |request| %>
      <tr>
        <td><%= request.created_at %></td>
        <td><%= request_status_badge(request.status) %></td>
        <td><%= request.page %></td>
        <td>
          <% if request.error? %>
            <%= link_to(FetchRequest.human_attribute_name("log"), '#', class: 'btn btn-sm btn-primary my-1', data: { controller:"modal", action: "modal#show", modal_id_param: 'fetch-request-log', modal_body_param: request.log }) %>
            <%= link_to(t('actions.restart'), fetch_request_path(request), class: 'btn btn-sm btn-primary my-1', data: { turbo_method: :put } ) %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>

<%= render("error_modal") %>

<% else %>
  <div><%= t('helpers.no_data') %></div>
<% end %>

app/views/fetch_requests/create.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>

app/views/fetch_requests/index.html.erb
<%= content_for(:breadcrumbs) do %>
  <% render("layouts/breadcrumbs/breadcrumbs", links: [{ title: t("navigation.settings"), url: setting_path }, { title: FetchRequest.model_name.human(count: 2) }]) %>
<% end %>

<h3><%= FetchRequest.model_name.human(count: 2) %></h3>

<%= turbo_frame_tag 'fetch_requests' do %>
  <%= render('records') %>
<% end %>

app/views/fetch_requests/update.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>