config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :setting, only: [:show]
  resource :data_source, only: [:edit, :update]

  resources :videos, only: [:index]
  resources :playlists
  resources :playlist_videos, only: [:create, :update, :destroy]

  resources :fetch_requests, only: [:index, :create, :update]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_videos, -> { ordered }, dependent: :destroy
  has_many :videos, through: :playlist_videos

  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }

  scope :order_by_name, -> { order(name: :asc)}
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  include VideosConcern

  before_action :find_playlist, only: [:show, :edit, :update, :destroy]

  def index
    scope = Playlist.order_by_name
    respond_to do |format|
      format.html do
        @pagy, @playlists = pagy(scope, items: 10)
      end
      format.json do
        @playlists = scope
      end
    end
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)

    if @playlist.save
      notice = t("flash.playlists.create.success")
      respond_to do |format|
        format.html { redirect_to @playlist, notice: notice }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json do
        get_videos(@playlist.videos)
        render "videos/index"
      end
    end
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      notice = t("flash.playlists.update.success")
      respond_to do |format|
        format.html { redirect_to @playlist, notice: notice }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_path, notice: t("flash.playlists.destroy.success") }
    end
  end

  private

  def find_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/views/playlists/_form.html.erb
<%= simple_form_for @playlist do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, @playlist.new_record? ? t("helpers.submit.create") : t("helpers.submit.update"), class: 'btn btn-primary mx-1' %>
  <%= link_to t("actions.cancel"), back_url, class: 'btn btn-secondary' %>
<% end %>

app/views/playlists/_index_hero.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold"><%= t('application_name') %></h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4"><%= t('playlists.index.hero') %></p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <%= link_to t("actions.create_playlist"), new_playlist_path, class: 'btn btn-primary btn-lg px-4 gap-3' %>
    </div>
  </div>
</div>

app/views/playlists/_show_hero.html.erb
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold"><%= t('application_name') %></h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4"><%= t('playlists.show.hero', name: @playlist.name) %></p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <%= link_to t("actions.add_videos"), root_path, class: 'btn btn-primary btn-lg px-4 gap-3' %>
    </div>
  </div>
</div>

app/views/playlists/edit.html.erb
<%= content_for(:breadcrumbs) do %>
  <% render("layouts/breadcrumbs/breadcrumbs",
            links: [
              { title: Playlist.model_name.human(count: 2), url: playlists_path },
              { title: truncate_link_title(@playlist.name), url: playlist_path(@playlist) },
              { title: t('actions.edit') }
            ]) %>
<% end %>

<h3><%= t('playlists.edit.title') %></h3>

<%= render 'form', back_url: playlist_path(@playlist) %>

app/views/playlists/index.html.erb
<% if @playlists.size > 0 %>
  <%= content_for(:breadcrumbs) do %>
    <% render("layouts/breadcrumbs/breadcrumbs", links: [{ title: Playlist.model_name.human(count: 2) }]) %>
  <% end %>

  <h3><%= Playlist.model_name.human(count: 2) %></h3>

  <%= link_to(t("actions.add"), new_playlist_path, class: "btn btn-primary my-2") %>

  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
      <tr>
        <th scope="col"><%= Playlist.human_attribute_name("name") %></th>
        <th scope="col"><%= Playlist.human_attribute_name("created_at") %></th>
        <th scope="col"></th>
      </tr>
      </thead>
      <tbody>
      <% @playlists.each do |playlist| %>
        <tr>
          <td><%= link_to(playlist.name, playlist_path(playlist)) %></td>
          <td><%= playlist.created_at %></td>
          <td>
            <%= link_to(t("actions.edit"), edit_playlist_path(playlist),  class: "btn btn-primary btn-sm my-1") %>
            <%= link_to(t("actions.delete"), playlist_path(playlist), data: { turbo_method: :delete, turbo_confirm: t("confirm.playlist.delete") },  class: "btn btn-danger btn-sm my-1") %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
<% else %>
  <%= render("index_hero") %>
<% end %>

app/views/playlists/new.html.erb
<%= content_for(:breadcrumbs) do %>
  <% render("layouts/breadcrumbs/breadcrumbs", links: [{ title: Playlist.model_name.human(count: 2), url: playlists_path }, { title: t('playlists.new.title')  }]) %>
<% end %>

<h3><%= t('playlists.new.title') %></h3>

<%= render 'form', back_url: playlists_path %>

app/views/playlists/show.html.erb
<%= content_for(:breadcrumbs) do %>
  <% render("layouts/breadcrumbs/breadcrumbs",
            links: [
              { title: Playlist.model_name.human(count: 2), url: playlists_path },
              { title: truncate_link_title(@playlist.name) }
            ]) %>
<% end %>

<h3>
  <%= @playlist.name %>
  <%= link_to(edit_playlist_path(@playlist), class: 'header-link') do %>
    <i class="bi bi-pencil"></i>
  <% end %>
  <%= link_to(playlist_path(@playlist), class: 'header-link text-danger', data: { turbo_method: :delete, turbo_confirm: t("confirm.playlist.delete") }) do %>
    <i class="bi bi-trash"></i>
  <% end %>
</h3>

<div
  id="playlist-video-list"
  data-videos-url="<%= playlist_url(@playlist, format: :json) %>"
  data-reorder-videos-url="<%= playlist_video_url(@playlist, format: :json) %>"
  data-remove-from-playlist-url="<%= playlist_video_url(@playlist, format: :json) %>"
  class="playlist-videos"
></div>