config/routes.rb
Rails.application.routes.draw do
  get 'homepage/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :setting, only: [:show]
  resource :data_source, only: [:edit, :update]

  resources :videos, only: [:index]
  resources :playlists
  resources :playlist_videos, only: [:create, :update, :destroy]

  resources :fetch_requests, only: [:index, :create, :update]

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message <%= flash_type_classes(flash_type) %>"
    data-controller="flash"
    data-flash-type="<%= flash_type %>"
    data-flash-message="<%= message %>"
  >
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer">
  <div class="copyright">
    © <%= Date.current.year %> <strong><%= link_to(Setting.dev_name, Setting.dev_url, target: "_blank") %></strong>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="logo d-flex align-items-center justify-content-between">
    <i class="bi bi-list toggle-sidebar-btn"
       data-controller="sidebar"
       data-action="click->sidebar#toggle"
    ></i>
    <%= link_to root_path, class: "d-flex align-items-center" do %>
      <span class="d-lg-block"><%= t("application_name") %></span>
    <% end %>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar" class="sidebar">

  <ul class="sidebar-nav" id="sidebar-nav">

    <li class="nav-item">
      <%= nav_link(t("navigation.home"), root_path, 'grid') %>
    </li>

    <li class="nav-item">
      <%= nav_link(t("navigation.playlists"), playlists_path, 'collection-play') %>
    </li>

    <li class="nav-item">
      <%= nav_link(t("navigation.settings"), setting_path, 'gear-wide-connected') %>
    </li>

  </ul>

  <%= render("layouts/footer") %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('application_name') %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="turbo-refresh-method" content="morph">
  <meta name="turbo-refresh-scroll" content="preserve">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
</head>

<body>

<%= render("layouts/header") %>
<%= render("layouts/sidebar") %>

<div id="flash" class="flash">
  <%= render "layouts/flash" %>
</div>

<main class="main" id=main>
  <%= yield :breadcrumbs %>

  <div>
    <%= yield %>
  </div>
</main>


</body>
</html>